common: &common
  port: 587
  authentication: "plain"
  enable_starttls_auto: true

development:
  en_mailer:
    <<: *common
    domain: "@mail.com"
    user_name: "d.spautz@mail.com"
    password: "P05st_Master"
    address: "smtp.mail.com" 
    from: 'd.spautz.mail.com'    
  de_mailer:
    <<: *common
    domain: "@web.de"
    user_name: "d.spautz@web.de"
    password: "P05st_Master"
    address: "smtp.web.de"
    from: 'd.spautz.web.de'
production:
  en_mailer:
    <<: *common
    domain: "mail.com"
    user_name: "d.spautz@mail.com"
    password: "P05st_Master"
    address: "smtp.mail.com"
    from: 'd.spautz.mail.com'
  de_mailer:
    <<: *common
    domain: "web.de"
    user_name: "d.spautz@web.de"
    password: "P05st_Master"
    address: "smtp.web.de"
    from: 'd.spautz.web.de'