common: &common
  port: 587
  authentication: "plain"
  enable_starttls_auto: true

development:
  en_mailer:
    <<: *common
    domain: "@mail.com"
    user_name: "example@mail.com"
    password: "****"
    address: "smtp.mail.com" 
    from: 'example.mail.com'    
  de_mailer:
    <<: *common
    domain: "@web.de"
    user_name: "example@web.de"
    password: "***"
    address: "smtp.web.de"
    from: 'example.web.de'
production:
  en_mailer:
    <<: *common
    domain: "mail.com"
    user_name: "example@mail.com"
    password: "***"
    address: "smtp.mail.com"
    from: 'example.mail.com'
  de_mailer:
    <<: *common
    domain: "web.de"
    user_name: "example@web.de"
    password: "***"
    address: "smtp.web.de"
    from: 'example.web.de'